version: '3.8'

services:
  youtube-uploader:
    image: youtube-uploader:latest
    command: ["node","index.js"]
    ports:
       - "${PORT}:${PORT}"
    volumes:
      - /tmp:/tmp
    deploy:
      replicas: 1
      restart_policy:
        condition: any
